Feature/rental service develop
f-lab-edu/wheel-go pull request #13
Opened 2024-12-04 15:30 UTC by ingyeomnote

## 📗요약
대여 기능을 구현하였습니다.

## 🛠️작업 사항

## 🗨️공유사항 to 리뷰어
JpaRepository를 상속받은 RentalRepository에서 JPA 메소드를 생성하면 exception just for purpose of providing stack trace 예외가 발생합니다.

2024-12-05 10:15 UTC, roam-f-lab requested changes

2024-12-05 10:17 UTC, prostars commented
logback 설정 추가해주세요.
스웨거 추가를 검토해주세요.

2024-12-06 06:50 UTC, ingyeomnote commented on build.gradle
> +    implementation 'org.hsqldb:hsqldb:2.6.1'
메모리에서 동작시 H2 DB보다 더 빠르다고 해서 선정했습니다.

2024-12-06 06:58 UTC, prostars commented on build.gradle
> +    implementation 'org.hsqldb:hsqldb:2.6.1'
현재 성능이 중요한 고려사항이 아니고, 메모리 디비는 개발 중에만 사용하실 예정 아닌가요? 로컬 테스트 환경의 메모리 디비는 주로 H2를 사용합니다. HSQL만의 기능이 필요한게 아니라면 이 부분은 다시 검토해 주세요.

2024-12-06 07:01 UTC, roam-f-lab commented on build.gradle
> +    implementation 'org.hsqldb:hsqldb:2.6.1'
현재 성능이 중요한 고려사항이 아니고, 메모리 디비는 개발 중에만 사용하실 예정 아닌가요? 로컬 테스트 환경의 메모리 디비는 주로 H2를 사용합니다. HSQL만의 기능이 필요한게 아니라면 이 부분은 다시 검토해 주세요.

2024-12-06 07:19 UTC, roam-f-lab commented
logback 설정 추가해주세요.
스웨거 추가를 검토해주세요.

2024-12-06 15:27 UTC, roam-f-lab commented on src/test/java/com/wheelgo/controller/RentalControllerTest.java
> +    void return_rent_dto_with_valid_qr_code() throws Exception {
카멜 형식으로로 맞춰주세요.

2024-12-07 01:58 UTC, roam-f-lab commented on src/main/resources/logback.xml
> +    <root level="DEBUG">
기본 로깅 레벨을 디버그로 맞추신 이유가 있을까요?

2024-12-12 13:31 UTC, roam-f-lab commented on build.gradle
> +    implementation 'org.springdoc:springdoc-openapi-ui:1.7.0' // OpenAPI 의존성
슬랙으로 관련 내용 메시지 남겼습니다. 확인해주세요.

2024-12-14 04:44 UTC, roam-f-lab commented on build.gradle
> +    implementation 'org.springdoc:springdoc-openapi-ui:1.7.0' // OpenAPI 의존성
springfox-swagger 의존성이 추가되었으니 springdoc-openapi-ui 의존성은 정리해주세요.

2024-12-17 03:32 UTC, roam-f-lab commented on src/test/java/com/wheelgo/controller/RentalControllerTest.java
> +    private RentalService rentalService;
DB 의존성 분리를 위해서 서비스 자체를 목킹하지 마시고, Repository 를 목킹하는 것으로 목킹의 범위를 좁혀주세요.

2024-12-18 03:50 UTC, ingyeomnote commented on src/test/java/com/wheelgo/controller/RentalControllerTest.java
> +    private RentalService rentalService;
repository 목킹으로 controller 테스트 코드를 작성할 수 있나요?

2024-12-18 10:14 UTC, roam-f-lab commented on src/test/java/com/wheelgo/controller/RentalControllerTest.java
> +    private RentalService rentalService;
repository를 모킹하면, 서비스를 실제 인스턴스로 사용할 수 있습니다.
지금은 서비스 별다른 비즈니스 로직이 없고 db 접근만을 하므로 크게 달라지지 않겠지만, 서비스 자체를 모킹하는 상황에서는 추후에 서비스에 비즈니스 로직이 들어갔을 때 테스트할 수 없습니다.

2024-12-19 03:00 UTC, roam-f-lab commented on src/test/java/com/wheelgo/controller/RentalControllerTest.java
> +    private RentalRepository rentalRepository;
여기만 수정하면 테스트가 동작하지 않습니다. 커밋의 단위는 기본적으로 동작이 되는 상태를 유지하는 것이 좋습니다.

2024-12-20 05:28 UTC, roam-f-lab approved these changes

2024-12-20 05:48 UTC, merged